[database]
user = "root"
password = "tulika"
host = "localhost"
database = "smart_warranty_db"

[firebase]
apiKey = "AIzaSyA8B0SUU_sHln_ltsSDE9vxJcIgZRHxDGQ"
authDomain = "smart-warranty-tracker.firebaseapp.com"
projectId = "smart-warranty-tracker"
storageBucket = "smart-warranty-tracker.firebasestorage.app"
messagingSenderId = "195865735455"
appId = "1:195865735455:web:2c1353501c7aafb847002a"
